openapi: 3.0.0
info:
  title: AI log schemas
  description: Schemas for logging services of AI assistant
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogSchema:
      title: Общая схема лога
      description: Общая схема лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        model:
          $ref: '#/components/schemas/ModelLogSchema'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogSchema'

    ModelLogSchema:
      title: Схема лога для микросервиса
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - train
            - predict
            - init
            - finish
        requestModel:
          $ref: '#/components/schemas/ModelLog'
        requestFilter:
          $ref: '#/components/schemas/ModelFilterLog'
        responseModel:
          $ref: '#/components/schemas/ModelLog'
        responseModels:
          type: array
          items:
            $ref: '#/components/schemas/ModelLog'

    ErrorLogSchema:
      title: Схема лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    ModelLog:
      title: Схема лога для модели
      type: object
      properties:
        id:
          type: string
        ownerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string
        features:
          type: array
          items:
            type: number
            format: double
        results:
          type: array
          items:
            type: number
            format: double
        title:
          type: string
        description:
          type: string
        solver_path:
          type: string
          description: Путь к внешнему КЭ решателю
        script_path:
          type: string
          description: Путь к входному макросу для запуска расчета
        params:
          type: array
          items:
            $ref: '#/components/schemas/ParamLog'
        visibility:
          type: string

    ParamLog:
      title: Схема лога для параметра
      type: object
      properties:
        param_type:
          type: string
        line:
          type: integer
        position:
          type: integer
        separator:
          type: string
        name:
          type: string
        bounds:
          $ref: '#/components/schemas/BoundsLog'

    BoundsLog:
      title: Схема лога для диапазона варьирования параметра
      type: object
      properties:
        min:
          type: double
        max:
          type: double

    ModelFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string